# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6904f4aa6ec3a0067f1d0a1a3f92f0e2ee41c65e83cf282c1b27a93d4588f862f0fed1bc065329b9ac7537bfe189f4d37ef343ad4954f1304028b941e7f8712c

test:
  secret_key_base: b57e016b68bcbc06c806aa1c516c82cdf5176d67677fb02f45b8735ceed7df7e082bf18dc24b9cf1247fbf9dc76c41ab8dde7426390432ab8a79e152524217f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
# used 'rails secret' generate secret key
production:
  secret_key_base: 5fa790339af9321e48a2b3288d75785f539c7ca29351b27aff57cd16463dc2dbd99fa85edcdf16c6a5cab9f223f61f2af1c1311210795db131f0f709b3d26ae1
